# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SAMUEL V
tagline:          Black Theme for Jekyll
description:      "Programador, Estudante, Autodidata, Back-end, Front-End, Cafécolatra, Web/Mobile, Designer Gráfico, Researcher Information Security."
url:              https://github.com/samverneck/samverneck.github.io
baseurl:          /

author:
  name:           'Samuel Fonseca Verneck'
  url:            https://github.com/samverneck

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:          https://github.com/samverneck/samverneck.github.io  


